### PR TITLE
[docker] Update GCC and Conan version

### LINKED ISSUE #96: [bug] Unable to setup Conan training
### Environment Details (include every applicable attribute)
  * Operating System+version:  Ubuntu 20.04
  * Compiler+version:  gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  * Conan version:1.48.0
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
git clone https://github.com/conan-io/training
cd training/docker_environment
docker-compose up -d
docker exec -it conan-training bash

### Logs (Executed commands with output) (Include/Attach if Applicable)

 2f103ac55ae1
Step 2/8 : USER root
 ---> Using cache
 ---> a5e0f1703b58
Step 3/8 : RUN apt-get -qq update     && apt-get -qq install -y --no-install-recommends        vim        nano        less        g++-arm-linux-gnueabihf        cmake
 ---> Running in bcc27843a78a
W: Failed to fetch http://old-releases.ubuntu.com/ubuntu/dists/artful/InRelease  Could not resolve 'old-releases.ubuntu.com'
W: Failed to fetch http://old-releases.ubuntu.com/ubuntu/dists/artful-updates/InRelease  Could not resolve 'old-releases.ubuntu.com'
W: Failed to fetch http://old-releases.ubuntu.com/ubuntu/dists/artful-backports/InRelease  Could not resolve 'old-releases.ubuntu.com'
W: Failed to fetch http://old-releases.ubuntu.com/ubuntu/dists/artful-security/InRelease  Could not resolve 'old-releases.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
E: Unable to locate package vim
E: Unable to locate package nano
E: Package 'less' has no installation candidate
E: Unable to locate package g++-arm-linux-gnueabihf
E: Couldn't find any package by regex 'g++-arm-linux-gnueabihf'
E: Package 'cmake' has no installation candidate
The command '/bin/sh -c apt-get -qq update     && apt-get -qq install -y --no-install-recommends        vim        nano        less        g++-arm-linux-gnueabihf        cmake' returned a non-zero code: 100

-->

### LINKED ISSUE #98: Exercise Consume with CMake: failure duing conan install
### Steps

1. git clone https://github.com/conan-io/training
2. cd training/docker_environment
3. docker-compose up -d
4. docker exec -it conan-training bash
5. cd consumer
6. mkdir build
7. cd build/
8. conan install ..

### Error

```
/data/learning/conan/training/docker_environment$ docker exec -it conan-training bash
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

conan@e62085c51e75:~/training$ cd consumer
conan@e62085c51e75:~/training/consumer$ mkdir build
conan@e62085c51e75:~/training/consumer$ cd build/
conan@e62085c51e75:~/training/consumer/build$ conan install ..
WARN: Remotes registry file missing, creating default one in /home/conan/.conan/remotes.json
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

boost/1.72.0: Not found in local cache, looking in remotes...
boost/1.72.0: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [1.35k]                                          
Downloading conanfile.py completed [79.28k]                                              
Downloading conan_export.tgz completed [1.48k]                                           
Decompressing conan_export.tgz completed [0.00k]                                         
boost/1.72.0: Downloaded recipe revision 0
zlib/1.2.12: Not found in local cache, looking in remotes...
zlib/1.2.12: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.33k]                                          
Downloading conanfile.py completed [4.19k]                                               
Downloading conan_export.tgz completed [0.31k]                                           
Decompressing conan_export.tgz completed [0.00k]                                         
zlib/1.2.12: Downloaded recipe revision 0
ERROR: zlib/1.2.12: Cannot load recipe.
Error loading conanfile at '/home/conan/.conan/data/zlib/1.2.12/_/_/export/conanfile.py': Unable to load conanfile in /home/conan/.conan/data/zlib/1.2.12/_/_/export/conanfile.py
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/conan/.conan/data/zlib/1.2.12/_/_/export/conanfile.py", line 1, in <module>
    from conan.tools.microsoft import is_msvc
ImportError: cannot import name 'is_msvc' from 'conan.tools.microsoft' (/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conan/tools/microsoft/__init__.py)`

```

### PR DESCRIPTION
**Pull request by uilianries**
- Use docker image `conanio/gcc11-ubuntu16.04:1.48.1`
- Update from GCC7 to GCC10
- Update from Conan 1.43.1 to 1.48.1
- Update Artifactory 7.11.5 to 7.38.10
- Remove Travis CI support (it's no longer free)
- Added Github Actions support

closes #96
closes #98

### CODE REVIEW

**Review by memsharded — APPROVED** [review]

**Comment by uilianries** [comment]
@memsharded All good now. We can check the exercise status directly from CI.

Please, note that I updated more things (all listed in PR description)

For now is running on my fork, but after merging it, it will run here too.

Current current is good: https://github.com/uilianries/conan-training/runs/6558999851?check_suite_focus=true

**Review by memsharded — COMMENTED** [review]
Looking good, just one question regarding zlib version

File: catchup.sh [hunk 1]
```diff
@@ -17,7 +17,7 @@ consumer() {
     cd bin
     ./timer
     conan search
-    conan search zlib/1.2.11@
+    conan search zlib/1.2.12@
```
[the remark this answers is not in the document]
Comment (uilianries) [reply catchup.sh:20]: Yes, it's possible. Let me some tests, because some them want 1.2.12, I guess they want the latest version available.

[the remark this answers is not in the document]
Comment (uilianries) [reply catchup.sh]: Now I get. We install Boost, which is updated now and will required 1.2.12. I'll keep 1.2.11 and only update those tests.

**Comment by uilianries** [comment]
Downgraded to GCC10 after some tests. The profile expected for Boost 1.72.0 is not available with GCC11 (it's expected as we avoid building old package versions).

Zlib will be 1.2.12 in some cases, but when it's a dependency, not the main package.

https://github.com/uilianries/conan-training/runs/6561117002?check_suite_focus=true

File: consumer/CMakeLists.txt [hunk 2]
```diff
@@ -7,5 +7,5 @@ include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
 conan_basic_setup(TARGETS)
 
 add_executable(timer timer.cpp)
-target_link_libraries(timer CONAN_PKG::poco
+target_link_libraries(timer CONAN_PKG::poco CONAN_PKG::hello
```
Comment (memsharded) [inline consumer/CMakeLists.txt:10]: This is not right, it shouldn't require here the ``CONAN_PKG::hello``

File: consumer/conanfile.txt [hunk 3]
```diff
@@ -1,4 +1,5 @@
-[requires]
+[requires]
+hello/0.1@user/testing
```
Comment (memsharded) [inline consumer/conanfile.txt:2]: It seems you are committing the changes after running the exercise.

File: consumer/timer.cpp [hunk 4]
```diff
@@ -5,6 +5,7 @@
 
 #include <string>
 #include <iostream>
+#include "hello.h"
```
Comment (memsharded) [inline consumer/timer.cpp:8]: Same, avoid these changes, they are the exercise

File: gtest/hello/conanfile.py [hunk 5]
```diff
@@ -7,7 +7,7 @@ class HelloConan(ConanFile):
     settings = "os", "compiler", "build_type", "arch"
     generators = "cmake"
     exports_sources = "*"
-    requires = "gtest/1.8.1"
+    build_requires =  "gtest/1.8.1"
```
Comment (memsharded) [inline gtest/hello/conanfile.py:10]: Avoid this change, this is the result of the exercise

File: lockfiles/hello/src/hello.cpp [hunk 6]
```diff
@@ -3,8 +3,8 @@
 
 void hello(){
     #ifdef NDEBUG
-    std::cout << "Hello World Release!" <<std::endl;
+    std::cout << "Hello World **** 0.2 **** Release!" <<std::endl;
```
Comment (memsharded) [inline lockfiles/hello/src/hello.cpp:6]: Same

File: package_id/hello/src/hello.h [hunk 7]
```diff
@@ -8,8 +8,8 @@
 
 inline void hello(){
     #ifdef NDEBUG
-    std::cout << "Hello World Release!" <<std::endl;
+    std::cout << "Hello World **** 1.1 **** Release!" <<std::endl;
```
Comment (memsharded) [inline package_id/hello/src/hello.h:11]: Same

File: myconfig/hooks/check_name.py [hunk 8]
```diff
@@ -6,4 +6,5 @@ def pre_export(output, conanfile, conanfile_path, reference, **kwargs):
     if ref.lower() != ref:
         raise Exception("Reference %s should be all lowercase" % ref)
     # use python "in" syntax.... if "something" in ref:
-    #TODO
+    if '-' in ref:
```
Comment (memsharded) [inline myconfig/hooks/check_name.py:9]: Same

File: requires_conflict/conanfile.txt [hunk 9]
```diff
@@ -1,3 +1,4 @@
 [requires]
+zlib/1.2.11
```
Comment (memsharded) [inline requires_conflict/conanfile.txt:2]: Same

**Review by memsharded — CHANGES_REQUESTED** [review]
Need to clean the changes from running the exercises

**Comment by uilianries** [comment]
The curse of git --all ... I gonna revert those changes, sorry.

File: docker_environment/docker-compose.yml [hunk 10]
```diff
@@ -1,25 +1,29 @@
...
-        networks:
-            - conan-training
-        ports:
-            - "8082:8082"
-        restart: always
-
-networks:
-    conan-training:
\ No newline at end of file
+version: "3.5"
```
Comment (uilianries) [inline docker_environment/docker-compose.yml:1]: It changed from CRLF to LF. It's hard to review, but only `CONAN_VERSION: ${CONAN_VERSION}` and `ARTIFACTORY_VERSION: ${ARTIFACTORY_VERSION}` have been added. The advantage is we can parametrize both versions to run locally or for future update.

**Comment by uilianries** [comment]
Good to go! 

The tests now are running into the training docker image.

https://github.com/uilianries/conan-training/runs/6570231090?check_suite_focus=true

**Review by memsharded — APPROVED** [review]

**Comment by memsharded** [comment]
Added some notes in the Academy course, hopefully those comments will avoid some support questions
